    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Tools (ImageMagick & FFmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ffmpeg
          # Cette ligne débloque les droits d'écriture d'ImageMagick sur Linux
          sudo sed -i 's/<policy domain="path" rights="none" pattern="@\*"/<policy domain="path" rights="read|write" pattern="@\*"/' /etc/ImageMagick-6/policy.xml

      - name: Install Python Dependencies
        run: |
          pip install moviepy==1.0.3 yt-dlp google-generativeai requests feedparser

      - name: Run Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py
